-- Add missing lot_size columns for all instruments
-- Run this as the postgres role in Supabase SQL Editor

ALTER TABLE trading_settings
  ADD COLUMN IF NOT EXISTS nas100_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS ger40_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS eurusd_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS gbpusd_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS eurgbp_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS eurjpy_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS gbpjpy_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS usdjpy_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS usdchf_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS usdcad_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS audusd_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS nzdusd_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS eth_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS uk100_lot_size DECIMAL(10,2) DEFAULT 0.01,
  ADD COLUMN IF NOT EXISTS spx500_lot_size DECIMAL(10,2) DEFAULT 0.01;
